xfail + skip

diff --git a/.github/workflows/partial.yaml b/.github/workflows/partial.yaml
--- a/.github/workflows/partial.yaml
+++ b/.github/workflows/partial.yaml
@@ -30,11 +30,16 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt
     - name: Run partial processing
+      id: main
       if: matrix.module != 'red' && matrix.module != 'zakazky' && matrix.module != 'eufondy'
       run: |
         python3 main.py --connstring sqlite:///data.db --partial ${{ matrix.module }}
     - name: Run partial processing (broken jobs)
-      if: matrix.module == 'red' || matrix.module == 'zakazky' || matrix.module == 'eufondy'
-      continue-on-error: true # TODO: mozna xfail nejak?
+      if: steps.main.conclusion == 'skipped'
       run: |
         python3 main.py --connstring sqlite:///data.db --partial ${{ matrix.module }}
+        exit_status=$?
+        if [ $exit_status -eq 0 ]; then
+          echo "Partial processing of ${{ matrix.module }} succeeded, but it should fail"
+          exit 1
+        fi
